mkdir Buried_exposed_alpha_helical_proteins
cd Buried_exposed_alpha_helical_proteins
mkdir ./scripts/
mkdir ./bash/
touch ./bash/runall.sh
touch ./bash/filter*sh
mkdir ./input/
mkdir ./logs
touch readme.txt
touch commands.txt
mkdir ./datasets/
mkdir ./general_scripts/
mkdir ./bin/